### ISSUE TITLE
Build and document the process for yunikorn-ui in C3

### ISSUE THREAD

**Issue by dave-gantenbein** [G-Research/yunikorn-history-server#124]
Documentation should be added to:
https://confluence.uberit.net/display/ASE/2.+Build+-+C3+Yunikorn+Runbook

**Comment by dcoric** [comment]
I managed to get a successful YK build in C3. The only issue is with dev dependencies as Jasmine is using Google Chrome as dependency for testing.


![Image](https://github.com/user-attachments/assets/d9b2e5e0-e121-4c25-a3fc-605c8e1d8976)

After switching the install command to `pnpm install --prod` I got partial success. Yunikorn put some dependencies to the dev group and it should be a part of the prod group like `angular-cli`.
I have rearranged those dependencies and got a successful install and build.

![Image](https://github.com/user-attachments/assets/a2f42b29-1690-47a4-a5b0-18122f287ee6)

The next step is to build a web from YHS and potentially arrange dependencies to fix any issues

**Comment by dcoric** [comment]
YuniKorn Web has switched to the `pnpm` from version 1.5

There are 2 ways to run the installation: 

1. install pnpm globally (if the system allows) with `npm i -g pnpm`
2. use `npx` to download a temp version of pnpm

As devDependencies pulls Google Chrome to run tests, it is not possible to do a full dependency installation.
For building and running a web project we need to install only the prod version of the dependencies.

Before executing that, 3 of the dependencies in the `package.json` file need to be shifted from `devDependencies` to `dependencies`:

```
    "@angular-devkit/build-angular": "^16.2.7",
    "@angular/cli": "^16.2.7",
    "@angular/compiler-cli": "^16.2.10",
```

after that run `npx pnpm install --prod` and this will install all of the required dependencies to build the project.
