### ISSUE TITLE
Generalize the `COALESCE` 

### ISSUE THREAD

**Issue by Mo-Fatah** [G-Research/yunikorn-history-server#13]
In a previous PR we added the [COALESCE](https://github.com/G-Research/yunikorn-history-server/blob/83f322c85c39248f708c653f013fd2d7c8ce8e6a/internal/repository/application.go#L13-L33) function to avoid nullifying any existing value in the database during upserts in the application table. Generalize this to all database upserts. 

https://www.postgresql.org/docs/current/functions-conditional.html#FUNCTIONS-COALESCE-NVL-IFNULL

**Comment by nikola-jokic** [comment]
Closing since event stream model is going to be different, so upserts are not necessary at this time
