### ISSUE TITLE
Unit testing for `internal/ykclient/api_handlers.go`

### ISSUE THREAD

**Issue by Mo-Fatah** [G-Research/yunikorn-history-server#15]
`api_handlers.go` seems solid for now. 
Add some https://github.com/G-Research/yunikorn-history-server/blob/main/internal/ykclient/api_handlers.go that will handle some corner cases from the YK scheduler such as connection failures and `404`

**Comment by richscott** [comment]
Fixed by https://github.com/G-Research/yunikorn-history-server/pull/64
