### ISSUE TITLE
Incorrect Implementation in Event Handler

### ISSUE THREAD

**Issue by sudiptob2** [G-Research/yunikorn-history-server#156]
## NOTE

Work for this ticket may depend upon https://github.com/G-Research/yunikorn-history-server/issues/164

## Background
In the App Event Handler, `partitionName` and `queueName` are not considered when retrieving the application, as seen in the code snippet on [line 80](https://github.com/G-Research/yunikorn-history-server/blob/88bc3935c26485c67b90e8056b0ef3d2adae5d1f/internal/yunikorn/event_handler.go#L75-L80) and [143](https://github.com/G-Research/yunikorn-history-server/blob/88bc3935c26485c67b90e8056b0ef3d2adae5d1f/internal/yunikorn/rest.go#L143-L145). Instead, the `partitionName` is replaced by `default`, which is unreliable since an application could be scheduled in a different partition.
https://github.com/G-Research/yunikorn-history-server/blob/88bc3935c26485c67b90e8056b0ef3d2adae5d1f/internal/yunikorn/event_handler.go#L75-L80
https://github.com/G-Research/yunikorn-history-server/blob/88bc3935c26485c67b90e8056b0ef3d2adae5d1f/internal/yunikorn/rest.go#L138-L145
## Problem
Ref: [Event Stream API](https://yunikorn.apache.org/docs/api/scheduler#event-stream)
The Event Stream API does not provide `partition` and `queueName` information when emitting a change event for a specific object. For application events, we need both `partition` and `queueName` to accurately identify and upsert the queue in our database.

## Solution
**Sol 1:**
Consider requesting the YuniKorn core to include additional information in the event stream. 🤞

> _From: Carig Condit (Yunikorn Maintainer)_ The API doesn't support your access pattern as it would require another layer of tracking to keep a global app list. That's more complexity when we don't need it for scheduling.

**Sol 2:** 
Search in all the partitions and collect all matching `application` with the particular `appId`. Then upsert them all.

**Comment by nikola-jokic** [comment]
Closing this issue since the event stream is changed to propagate the information about the object
