### ISSUE TITLE
[helm-chart installation] history-server installation with helm chart fail

### ISSUE THREAD

**Issue by 0yukali0** [G-Research/yunikorn-history-server#165]
# What is this issue?
micro-service mode fails.

# How to reproduce?
```
make kind-all
helm install history-server chart -n yunikorn
```

# Screenshots
![image](https://github.com/user-attachments/assets/9d238c03-ff12-4675-9607-871109f951e6)
![image](https://github.com/user-attachments/assets/5d72a341-4f0d-475c-91fc-1c606bd9e797)

**Comment by sudiptob2** [comment]
solved in #166
