### ISSUE TITLE
CI workflows should run tests first, and not proceed to build job if former fails

### ISSUE THREAD

**Issue by richscott** [G-Research/yunikorn-history-server#172]
A recent PR had its CI checks run, and the Golang unit tests failed quickly, due to a transient race condition bug causing a Go runtime panic,  however the build workflows continued to run, so we had to wait until they were finished before the "Re-run (failed) jobs" button became available. 

Since the race-condition bug was severe - it would disastrous if this happened in the deployed application - we probably should not bother running the `build` job(s) of the workflows, and just have the CI workflows fail immediately if the unit-tests or integration tests fail.

**Comment by pavlovic-ivan** [comment]
There are two options, here:
1. We can `fail-fast` the workflow, if a job fails, test job in this case, which will make the "Re-run jobs" available
2. Order the jobs, so that build is not run before nor in parallel with test job

Which one would you prefer?
