### ISSUE TITLE
Modify sync logic to use new queue-related DB funcs

### ISSUE THREAD

**Issue by richscott** [G-Research/yunikorn-history-server#178]
Modify the `internal/yunikorn/sync.go` - in `upsertPartitionQueues()` - the steps are:
- query db for all non-deleted queues it has stored
        - for each non-deleted queue in db,  if the YK response does not list that queue, call DeleteQueue()
        with that queue as argument
- for each queue in YK response, check if queue is in YHS db by calling GetQueue(ctx, partition, queueName)
        - if not, call AddQueue(ctx, queues)
        - if it is in the db, call UpdateQueue(ctx, queueID, queueDAO)

**Comment by sudiptob2** [comment]
done in https://github.com/G-Research/yunikorn-history-server/pull/221
