### ISSUE TITLE
YHS: use env vars for event-collector config if no yhs.yml specified

### ISSUE THREAD

**Issue by richscott** [G-Research/yunikorn-history-server#22]
For when we eventually start using container-based YHS instances, the `event-collector` should search for and use environment variables for its settings, so a static container image can be used, and we inject the settings via pod env settings.

Alternately, for deployments, we could also do some sort of volume-mount of the config YML file on the YHS pod.

**Comment by sudiptob2** [comment]
Hi, This issue seems interesting to me. Please assign it to me if you think it is something I can work on 😊

**Comment by richscott** [comment]
@sudiptob2 Excellent! I have assigned it to you. It should be not very difficult to also support using the built-in env vars support that the `koanf` library we are using for configs - see https://github.com/knadh/koanf?tab=readme-ov-file#reading-environment-variables

Thanks.

**Comment by sudiptob2** [comment]
Thanks for the hint. Will start working on it.

**Comment by sudiptob2** [comment]
Hi, @richscott 
Wanted to confirm a few cases. `koanf` supports merging env variables from different sources. Should we also consider the following cases? Or we should only look into env vars if a configuration file is not passed.
1. Some configuration is defined in `.yaml` and others are passed as ENV VARs
2. yaml is passed but variables are also defined as ENV VARS, so ENV VARs should take precedence over `.yaml` config file.

**Comment by sudiptob2** [comment]
Thank you so much for the details.
