### ISSUE TITLE
Unsatisfied version 16.2.10 from yunikorn-web of shared singleton module @angular/core (required ^18.2.2)

### ISSUE THREAD

**Issue by zj619** [G-Research/yunikorn-history-server#232]
![image](https://github.com/user-attachments/assets/e32a0ff8-22ac-44c4-9540-bde0f417b7b3)

when deploy yunikorn-history-server with yunikorn 1.6.0，the web ui console shows error message "Unsatisfied version 16.2.10 from yunikorn-web of shared singleton module @angular/core (required ^18.2.2)"，seems to be dependency conflict，anyone solved this before?

**Comment by dcoric** [comment]
Thank you for reporting the issue. We have identified the dependency conflict and resolved it. The code fix is now available in the main branch.

The problem was with the dependencies mapped in `webpack.config.js` - they must have matching versions on the YuniKorn side.
