### ISSUE TITLE
YHS: add database schema migration tooling

### ISSUE THREAD

**Issue by dave-gantenbein** [G-Research/yunikorn-history-server#57]
Currently, the Yunikorn History Service codebase has its database schema hardcoded directly into internal/event-collector/repository/postgres.go, and uses direct pgx.Exec calls to issue the SQL commands to create/update the database schema.

We should switch to having the SQL in separate files, so recompilation of the service code is not necessary, and start tracking database schema versions. Suggest that we use the migrate library and tool at https://github.com/golang-migrate/migrate, which is very mature and well-supported.

**Comment by nikola-jokic** [comment]
Closed with #68
