### ISSUE TITLE
Bug🐛: Incorrect JSON parsing in `GetPartitionQueues()`

### ISSUE THREAD

**Issue by sudiptob2** [G-Research/yunikorn-history-server#65]
`/ws/v1/partition/{partitionName}/queues` returns ques as a JSON array. But in the `GetPartitionQueues()` we are trying to unmarshal the JSON incorrectly. 
Please take a look at the following code snippet. We are trying to parse the response as a single JSON, not a JSON array. Therefore, it will always return unmarshal error.
https://github.com/G-Research/yunikorn-history-server/blob/573d2757870458469f0322c592081241e59b5874/internal/ykclient/api_handlers.go#L92-L110

**Comment by sudiptob2** [comment]
I investigated the issue further and believe the `ynikorn` [documentation](https://yunikorn.apache.org/docs/api/scheduler/#partition-queues) is incorrect. The API actually returns a single JSON object, so our implementation is correct. See the response from `ynikorn` running on my local cluster in the below screenshot.

<img width="650" alt="image" src="https://github.com/G-Research/yunikorn-history-server/assets/32765701/ef1078df-9a3d-4b3b-ad7f-fa3c4776576d">

**Comment by nikola-jokic** [comment]
Closing this one as done. The rest of the work is tracked with #215 and #216
