### ISSUE TITLE
Use 'yhs' as default Postgres database instance name for YHS services

### ISSUE THREAD

**Issue by richscott** [G-Research/yunikorn-history-server#84]
It's bad practice - very, very bad practice - to use the `postgres` db instance for a running service, unless you explicitly need to instantiate new db instances as part of run-time operations. The YHS service should use `yhs` or any other name that is not in the set `(postgres, template0, template1)` for its database.

**Comment by dejanzele** [comment]
I'd keep it simple for quickstart and localdev and use the defaults, but use more finer settings in remote envs
